version: "3.8"
services:
  server:
    build:
      context: .
      args:
          UID: ${UID}
          GID: ${GID}          
    container_name : "${USER}_server"
    env_file: .env
    ports:
      - "${HOST_IP}:${HOST_PORT}:${CONTAINER_PORT}"
      - "${HOST_IP}:${HOST_API_PORT}:${CONTAINER_API_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - ./data:/home/user/shared_data
    ipc: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
